FROM quay.io/toolbx-images/alpine-toolbox:latest

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience" \
      maintainer="noahdotpy@proton.me"

COPY toolboxes/mybox/extra-packages /
RUN apk update && \
    cat /extra-packages | xargs apk add
RUN rm /extra-packages

RUN ln -fs /bin/sh /usr/bin/sh && \

    # Use host for these directories
    ln -fs /run/host/nix /nix && \

    # Use host for these binaries
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/distrobox && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/nix && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/ujust

